create table CovidVaccinations(
	iso_code varchar(250),
	continent varchar(250),
	location varchar(250),
	date date,
	new_tests int,
	total_tests	int,
	total_tests_per_thousand float,
	new_tests_per_thousand float,
	new_tests_smoothed int,
	new_tests_smoothed_per_thousand	float,
	positive_rate float,
	tests_per_case float,
	tests_units	varchar(250),
	total_vaccinations bigint,
	people_vaccinated bigint,
	people_fully_vaccinated	bigint,
	total_boosters bigint,
	new_vaccinations int,
	new_vaccinations_smoothed int,
	total_vaccinations_per_hundred float,
	people_vaccinated_per_hundred float,
	people_fully_vaccinated_per_hundred float,
	total_boosters_per_hundred float,
	new_vaccinations_smoothed_per_million int,
	new_people_vaccinated_smoothed int,
	new_people_vaccinated_smoothed_per_hundred	float,
	stringency_index float,
	population_density float,
	median_age	float,
	aged_65_older	float,
	aged_70_older	float,
	gdp_per_capita float,
	extreme_poverty	float,
	cardiovasc_death_rate	float,
	diabetes_prevalence float,
	female_smokers float,
	male_smokers float,
	handwashing_facilities float,
	hospital_beds_per_thousand float,
	life_expectancy	float,
	human_development_index	float,
	excess_mortality_cumulative_absolute decimal,
	excess_mortality_cumulative decimal,
	excess_mortality decimal,
	excess_mortality_cumulative_per_million decimal
);


COPY public.covidvaccinations from 'E:\EPITA_Relation_DB\CovidVaccinations.csv' DELIMITER ',' CSV HEADER;